### ISSUE TITLE
Error tracking number 

### ISSUE THREAD

**Issue by Rkcoder0425** [IccTeam/Owl-sint#2]
When we select v2 type this error come.                   
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Owl-sint/owlsint.py", line 402, in <module>
    start()
  File "/data/data/com.termux/files/home/Owl-sint/owlsint.py", line 162, in start
    print(f"{YELLOW}Valid                 {NORMAL}:{GREEN} " + str(phe.json() ['valid']))
                                                                   ~~~~~~~~~~~^^^^^^^^^
KeyError: 'valid'



Help me please

**Comment by Rkcoder0425** [comment]
Also this one 

[1] Phone Number Information
         [2] Track IP
         [3] Instagram User Information
         [A] About
           Choose: 1

        [1] Track Number V1
        [2] Track Number V2
        [3] Track Number V3
      Choose: 1
Enter Number (Without +) :➤ 03480890841
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Owl-sint/owlsint.py", line 402, in <module>
    start()
  File "/data/data/com.termux/files/home/Owl-sint/owlsint.py", line 95, in start
    parsing = parse(number)
              ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/phonenumbers/phonenumberutil.py", line 2941, in parse
    raise NumberParseException(NumberParseException.INVALID_COUNTRY_CODE,
phonenumbers.phonenumberutil.NumberParseException: (0) Missing or invalid default region.
Help me

**Comment by 0xMimisco** [comment]
how do i start this owl sint
